### ISSUE TITLE
bplistings module

### ISSUE THREAD

**Issue by lo8888** [Nicklason/tf2-automatic#138]
The bot could not update its price after 30 minutes. Could be the issue about bplistings module error. 

Photo of the error: http://imgur.com/gallery/AId5JJi

**Comment by ZeusJunior** [comment]
If you are running with pm2, its a good idea to have it restart every hour or so. Usually fixes this issue

**Comment by lo8888** [comment]
Yes !restart in the chat command fixed the issue but by the time right now, I need to manually restart it every 30 or so minutes and I wish it could be fixed in the upcoming update/patch with automatically update price.

**Comment by ZeusJunior** [comment]
Add 
`setTimeout(function(){
    process.exit(1)
}, 60 * 60 * 1000);`
To automatic.js to make it quit every hour. Pm2 will restart it

**Comment by lo8888** [comment]
Okay thanks for the assistance

**Comment by Nicklason** [comment]
The image you linked does not show any kind of error. But yes, I have known this problem for a long time, and I still blame fisk.

**Comment by lo8888** [comment]
So that means we need wait fisk to fix the issue on backpack.tf side before returning back to normal?

**Comment by Nicklason** [comment]
No. I’ll fix it, just not right now.

**Comment by Nicklason** [comment]
Fixed in https://github.com/Nicklason/tf2-automatic/tree/v2

**Comment by swinarga** [comment]
@Nicklason I'm still having this issue but its with buy order listings only. 
![Screen Shot 2020-04-19 at 18 48 57](https://user-images.githubusercontent.com/53258224/79694184-1a278600-826f-11ea-9554-66f7b8311cab.png)
![Screen Shot 2020-04-19 at 18 49 02](https://user-images.githubusercontent.com/53258224/79694185-1bf14980-826f-11ea-87d3-f0d7a722983e.png)
!update all=true or restarting the bot fixes this issue.
